# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lSSrwLUnQBc63ICSZgjkefDZg5bNPOXZ
"""

!pip install transformers torch nltk --quiet
import nltk
nltk.download('vader_lexicon')

# ---------------- SENTIMENT LOGIC ---------------- #
from transformers import pipeline
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import numpy as np

try:
    hf_model = pipeline("sentiment-analysis")
except:
    hf_model = None

vader = SentimentIntensityAnalyzer()

def analyze_sentiment(text):
    text = text.strip()
    if not text:
        return {"label": "NEUTRAL", "score": 0.0}

    # Try HF model first
    if hf_model:
        res = hf_model(text[:512])[0]
        return {
            "label": res["label"].upper(),
            "score": float(res["score"])
        }

    # Otherwise fallback Vader
    score = vader.polarity_scores(text)["compound"]
    if score >= 0.05:
        return {"label": "POSITIVE", "score": score}
    elif score <= -0.05:
        return {"label": "NEGATIVE", "score": abs(score)}
    else:
        return {"label": "NEUTRAL", "score": abs(score)}


# ---------------- CHATBOT SYSTEM ---------------- #
class SentimentChatbot:
    def __init__(self):
        self.history = []  # stores (text, sentiment)

    def respond_to(self, user_msg):
        sentiment = analyze_sentiment(user_msg)
        self.history.append(sentiment)

        # Simple replies based on sentiment
        if sentiment['label'] == "NEGATIVE":
            return "I'm sorry to hear that. Can you tell me more?", sentiment
        elif sentiment['label'] == "POSITIVE":
            return "That's great to hear! What else would you like to share?", sentiment
        else:
            return "I get it. Please continue.", sentiment

    def overall_sentiment(self):
        pos = sum(1 for s in self.history if s['label']=="POSITIVE")
        neg = sum(1 for s in self.history if s['label']=="NEGATIVE")
        neu = sum(1 for s in self.history if s['label']=="NEUTRAL")

        total = len(self.history)
        if total == 0:
            return "NEUTRAL", 0.0

        if pos > neg:
            final = "POSITIVE"
        elif neg > pos:
            final = "NEGATIVE"
        else:
            final = "NEUTRAL"

        score = round((pos - neg) / total, 3)
        return final, score


# ---------------- RUN INTERACTIVE CHATBOT ---------------- #
bot = SentimentChatbot()

print("🤖 Chatbot started! Type 'exit' to finish.\n")

while True:
    user = input("You: ")
    if user.lower() == "exit":
        final_label, final_score = bot.overall_sentiment()
        print("\n📌 Final Overall Sentiment:", final_label, "| Score:", final_score)
        print("Goodbye! 👋")
        break

    reply, senti = bot.respond_to(user)
    print(f"Bot: {reply}")
    print(f"🔍 Sentiment => {senti['label']} ({senti['score']})\n")

